{% set name = "sliderule" %}
{% set version = "1.3.2" %}
{% set sha256 = "aadbad9c6cea0f6bedac20ba5fb6bce5ea232d9c2eb0b7e253b5485c5313c98a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
    - setuptools
  run:
    - cartopy
    - geopandas
    - h5py
    - ipykernel
    - ipyleaflet
    - ipywidgets
    - matplotlib-base
    - numpy
    - pandas
    - pyproj
    - python >=3.6
    - python-dateutil
    - requests
    - scipy
    - setuptools-scm
    - setuptools
    - shapely
    - tk

test:
  imports:
    - sliderule
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://icesat2sliderule.org/
  summary: Python client for SlideRule
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Python client to interact with SlideRule, a C++/Lua framework for on-demand data processing
  doc_url: http://icesat2sliderule.org/rtd/
  dev_url: https://github.com//ICESat2-SlideRule/sliderule-python

extra:
  recipe-maintainers:
    - tsutterley
    - jpswinski
    - dshean
