{% set name = "sliderule" %}
{% set version = "4.8.5" %}
{% set sha256 = "f15a3e08d6b140a5e37fb4d4e714f2259dd09e7fdfd4d364de85b23d45c6da87" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - geopandas
    - numpy
    - pandas
    - python >=3.8
    - requests
    - shapely
    - fiona
    - pyarrow

test:
  imports:
    - sliderule
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://slideruleearth.io/
  summary: Python client for SlideRule
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Python client to interact with SlideRule, a public web service for processing Earth science data
  doc_url: http://slideruleearth.io/rtd/
  dev_url: https://github.com/SlideRuleEarth/sliderule

extra:
  recipe-maintainers:
    - dshean
    - jpswinski
    - scottyhq
    - tsutterley
