{% set name = "sliderule" %}
{% set version = "1.5.7" %}
{% set sha256 = "bd3170276f7d74d3e3af027ff3bda09c728ffa26869974eb479efb6cc10e7590" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - geopandas
    - h5py
    - ipykernel
    - ipywidgets >=7.6,<8.0
    - ipyleaflet >=0.15
    - jupyterlab =3
    - jupyterlab_widgets
    - matplotlib-base
    - ipympl
    - numpy
    - pandas
    - pyproj
    - pytables
    - python >=3.8
    - requests
    - scikit-learn
    - scipy
    - setuptools_scm
    - shapely
    - tk
    - xyzservices

test:
  imports:
    - sliderule
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://slideruleearth.io/
  summary: Python client for SlideRule
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Python client to interact with SlideRule, a C++/Lua framework for on-demand data processing
  doc_url: http://slideruleearth.io/rtd/
  dev_url: https://github.com//ICESat2-SlideRule/sliderule-python

extra:
  recipe-maintainers:
    - dshean
    - jpswinski
    - scottyhq
    - tsutterley
