{% set name = "sliderule" %}
{% set version = "1.1.4" %}
{% set sha256 = "0b1c997db2f60002c9cd78a439d0e98ee8f1e1ce4d598d50c90a2128a89e712d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
    - setuptools
  run:
    - cartopy
    - geopandas
    - h5py
    - ipykernel
    - ipyleaflet
    - ipywidgets
    - jupyterlab =3
    - jupyterlab_widgets
    - matplotlib-base
    - numpy
    - pandas
    - pyproj
    - python >=3.8
    - python-dateutil
    - requests
    - scipy
    - setuptools-scm
    - setuptools
    - shapely
    - tk

test:
  imports:
    - sliderule
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://icesat2sliderule.org/
  summary: Python client for SlideRule
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Python client to interact with SlideRule, a C++/Lua framework for on-demand data processing
  doc_url: http://icesat2sliderule.org/rtd/
  dev_url: https://github.com//ICESat2-SlideRule/sliderule-python

extra:
  recipe-maintainers:
    - tsutterley
    - jpswinski
    - dshean
