{% set name = "sliderule" %}
{% set version = "5.0.0" %}
{% set sha256 = "a194d134dfc940c453cdd798a4437a8788b2dbe6e426551b9e8ec67ee2b57c2e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - geopandas
    - numpy
    - pandas
    - requests
    - shapely
    - fiona
    - pyarrow

test:
  imports:
    - sliderule
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://slideruleearth.io/
  summary: Python client for SlideRule
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Python client to interact with SlideRule, a public web service for processing Earth science data
  doc_url: http://slideruleearth.io/rtd/
  dev_url: https://github.com/SlideRuleEarth/sliderule

extra:
  recipe-maintainers:
    - dshean
    - jpswinski
    - scottyhq
    - tsutterley
