{% set name = "sliderule" %}
{% set version = "1.5.1" %}
{% set sha256 = "c18ab4beb7dc60e46537edeeb878d5f01f0fb7ce917e7b440cd3c08ff08d4d35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - geopandas
    - gdal
    - h5py
    - ipykernel
    - ipyleaflet
    - ipywidgets
    - matplotlib-base
    - ipympl
    - numpy
    - pandas
    - pyproj
    - pytables
    - python >=3.6
    - python-dateutil
    - requests
    - scipy
    - setuptools
    - shapely
    - tk
    - traitlets
    - xyzservices

test:
  imports:
    - sliderule
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://icesat2sliderule.org/
  summary: Python client for SlideRule
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Python client to interact with SlideRule, a C++/Lua framework for on-demand data processing
  doc_url: http://icesat2sliderule.org/rtd/
  dev_url: https://github.com//ICESat2-SlideRule/sliderule-python

extra:
  recipe-maintainers:
    - dshean
    - jpswinski
    - scottyhq
    - tsutterley
