{% set name = "sliderule" %}
{% set version = "3.1.0" %}
{% set sha256 = "c7fd79e4531041046b2bd5b35188e38c819e446a9ab92fa34a0cfdffc24e781f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - geopandas
    - numpy
    - pandas
    - pyarrow
    - python >=3.8
    - requests
    - setuptools_scm
    - shapely

test:
  imports:
    - sliderule
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://slideruleearth.io/
  summary: Python client for SlideRule
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Python client to interact with SlideRule, a C++/Lua framework for on-demand data processing
  doc_url: http://slideruleearth.io/rtd/
  dev_url: https://github.com//ICESat2-SlideRule/sliderule

extra:
  recipe-maintainers:
    - dshean
    - jpswinski
    - scottyhq
    - tsutterley
