{% set name = "sliderule" %}
{% set version = "4.15.5" %}
{% set sha256 = "fc7641a41f3bb9ed5760810e42f821a1bac6592b4078d352e3f678073a852a5e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - geopandas
    - numpy
    - pandas
    - python >={{ python_min }}
    - requests
    - shapely
    - fiona
    - pyarrow

test:
  imports:
    - sliderule
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://slideruleearth.io/
  summary: Python client for SlideRule
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Python client to interact with SlideRule, a public web service for processing Earth science data
  doc_url: http://slideruleearth.io/rtd/
  dev_url: https://github.com/SlideRuleEarth/sliderule

extra:
  recipe-maintainers:
    - dshean
    - jpswinski
    - scottyhq
    - tsutterley
